version: "3"

services:
  no-app1:
    build: .
    environment:
      - PORT=5001

  no-app2:
    build: .
    environment:
      - PORT=5002

  no-app3:
    build: .
    environment:
      - PORT=5003

  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - no-app1
      - no-app2
      - no-app3
